version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:
### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}:/var/lib/postgresql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "${POSTGRES_PORT}:5432"
      restart: "no"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend

    adminer:
      image: adminer
      restart: "no"
      ports:
        - ${ADMINER_PORT}:8080
      networks:
        - backend
